name: Update Chain Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:         # Manual trigger

permissions:
  issues: write
  contents: read

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Test Connection
        run: |
          echo "Testing API connection..."
          response=$(curl -v -s \
            -H "x-api-key: ${{ secrets.UPDATE_API_KEY }}" \
            "https://backend-phi-green.vercel.app/api/test")
          echo "Raw response: $response"
          
          # Only try to parse if we got a response
          if [ ! -z "$response" ]; then
            if echo "$response" | jq -e . >/dev/null 2>&1; then
              if echo "$response" | jq -e '.success == true' >/dev/null; then
                echo "API test passed"
              else
                echo "API test failed: Response indicates failure"
                exit 1
              fi
            else
              echo "API test failed: Invalid JSON response"
              exit 1
            fi
          else
            echo "API test failed: Empty response"
            exit 1
          fi

      - name: Update All Data
        id: update
        if: success()
        run: |
          echo "Attempting first update..."
          response=$(curl -s -X POST \
            -H "x-api-key: ${{ secrets.UPDATE_API_KEY }}" \
            -H "Content-Type: application/json" \
            "https://backend-phi-green.vercel.app/api/update/batch")
          
          echo "Raw update response: $response"
          
          if [ ! -z "$response" ] && echo "$response" | jq -e '.success == true' >/dev/null; then
            echo "Update process started successfully"
            echo "Waiting for 30 seconds to allow processing..."
            sleep 30
          else
            echo "Update initiation failed: $response"
            exit 1
          fi
          
          # Check the health endpoint
          health_response=$(curl -s \
            -H "x-api-key: ${{ secrets.UPDATE_API_KEY }}" \
            "https://backend-phi-green.vercel.app/api/health")
            
          echo "Raw health response: $health_response"
          
          if [ ! -z "$health_response" ] && echo "$health_response" | jq -e '.success == true' >/dev/null; then
            echo "Health check passed"
          else
            echo "Health check failed: $health_response"
            exit 1
          fi

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Data Update Failed',
              body: `Update job failed at ${new Date().toISOString()}\nPlease check the GitHub Actions logs.`
            })